"""addinf foreignkey

Revision ID: 219c93089fb7
Revises: 74e4a5a4d413
Create Date: 2019-03-07 16:10:47.178774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219c93089fb7'
down_revision = '74e4a5a4d413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'sites', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'site_id')
    # ### end Alembic commands ###
