"""addinf foreignkey

Revision ID: 74e4a5a4d413
Revises: 1afe121776e0
Create Date: 2019-03-07 16:09:46.143757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e4a5a4d413'
down_revision = '1afe121776e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_site_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'site_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_site_id_fkey', 'comments', 'sites', ['site_id'], ['id'])
    # ### end Alembic commands ###
