"""Initial Migration

Revision ID: 97144ce110e6
Revises: 
Create Date: 2019-03-06 19:10:15.060159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97144ce110e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('places', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('images', sa.String(length=225), nullable=True),
    sa.Column('maps_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['maps_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    op.drop_table('maps')
    # ### end Alembic commands ###
