"""add category in site model

Revision ID: f980eaba9a12
Revises: 97144ce110e6
Create Date: 2019-03-07 09:16:29.841800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f980eaba9a12'
down_revision = '97144ce110e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'category')
    # ### end Alembic commands ###
